"""
Agent 5b: Industry Intelligence — maps generic analysis results onto
industry-specific KPIs and recommendation language.

This is deliberately deterministic/template-based rather than another LLM
call: it's faster, free, and the KPI definitions for "what matters in
banking" don't really need to be regenerated by an AI each time. Column
name matching is heuristic (case-insensitive substring match) since real
datasets name things inconsistently.
"""

INDUSTRIES = ["banking", "finance", "retail", "healthcare", "education", "manufacturing", "hr"]

_KPI_DEFINITIONS = {
    "banking": [
        {"name": "Default / Churn Rate", "keywords": ["default", "churn", "closed"]},
        {"name": "Credit Risk Score", "keywords": ["credit_score", "risk_score", "fico"]},
        {"name": "Loan Approval Rate", "keywords": ["approved", "loan_status"]},
        {"name": "Average Account Balance", "keywords": ["balance"]},
        {"name": "Transaction Volume", "keywords": ["transaction", "txn"]},
    ],
    "finance": [
        {"name": "Revenue Growth", "keywords": ["revenue", "sales"]},
        {"name": "Profit Margin", "keywords": ["profit", "margin"]},
        {"name": "Expense Ratio", "keywords": ["expense", "cost"]},
        {"name": "Cash Flow", "keywords": ["cash_flow", "cashflow"]},
        {"name": "ROI", "keywords": ["roi", "return"]},
    ],
    "retail": [
        {"name": "Sales per Customer", "keywords": ["sales", "revenue"]},
        {"name": "Inventory Turnover", "keywords": ["inventory", "stock"]},
        {"name": "Customer Retention", "keywords": ["repeat", "retention", "churn"]},
        {"name": "Average Order Value", "keywords": ["order_value", "basket"]},
        {"name": "Return Rate", "keywords": ["return", "refund"]},
    ],
    "healthcare": [
        {"name": "Readmission Rate", "keywords": ["readmission", "readmit"]},
        {"name": "Diagnosis Accuracy Signal", "keywords": ["diagnosis", "outcome"]},
        {"name": "Average Length of Stay", "keywords": ["length_of_stay", "los", "stay"]},
        {"name": "Patient Risk Score", "keywords": ["risk", "severity"]},
        {"name": "Treatment Cost", "keywords": ["cost", "billing", "charge"]},
    ],
    "education": [
        {"name": "Dropout / Attrition Rate", "keywords": ["dropout", "attrition", "withdraw"]},
        {"name": "Average Grade / GPA", "keywords": ["gpa", "grade", "score"]},
        {"name": "Attendance Rate", "keywords": ["attendance", "absent"]},
        {"name": "Pass Rate", "keywords": ["pass", "result"]},
        {"name": "Engagement Signal", "keywords": ["engagement", "participation"]},
    ],
    "manufacturing": [
        {"name": "Defect Rate", "keywords": ["defect", "fault", "reject"]},
        {"name": "Downtime", "keywords": ["downtime", "outage"]},
        {"name": "Throughput", "keywords": ["throughput", "output", "units"]},
        {"name": "Cycle Time", "keywords": ["cycle_time", "duration"]},
        {"name": "Maintenance Cost", "keywords": ["maintenance", "repair"]},
    ],
    "hr": [
        {"name": "Attrition Rate", "keywords": ["attrition", "left", "turnover", "churn"]},
        {"name": "Average Tenure", "keywords": ["tenure", "years_at"]},
        {"name": "Performance Rating", "keywords": ["performance", "rating"]},
        {"name": "Satisfaction Score", "keywords": ["satisfaction", "engagement"]},
        {"name": "Time to Hire", "keywords": ["time_to_hire", "hiring"]},
    ],
}

_RECOMMENDATION_TEMPLATES = {
    "banking": "Flag accounts above the {col} threshold of {value} for manual underwriting review.",
    "finance": "Re-forecast {col} for next quarter using the trend identified in this model — current trajectory suggests {direction}.",
    "retail": "Prioritize restocking for segments with high {col} and low fulfillment to avoid lost sales.",
    "healthcare": "Route patients with {col} in the top risk decile to care coordination follow-up.",
    "education": "Set up an early-warning trigger for students whose {col} falls below {value}.",
    "manufacturing": "Schedule preventive maintenance for lines showing {col} trending past {value}.",
    "hr": "Open a retention conversation with employees whose {col} pattern matches the at-risk segment found here.",
}


def _match_columns(columns: list, keywords: list) -> list:
    cols_lower = [c.lower() for c in columns]
    matches = []
    for kw in keywords:
        for orig, low in zip(columns, cols_lower):
            if kw in low and orig not in matches:
                matches.append(orig)
    return matches


def get_industry_insights(industry: str, det: dict, ana: dict, ml: dict) -> dict:
    industry = (industry or "").strip().lower()
    if industry not in _KPI_DEFINITIONS:
        return {"available": False, "industry": industry}

    columns = det.get("columns", [])
    stats = det.get("column_stats", {})
    kpi_results = []
    for kpi in _KPI_DEFINITIONS[industry]:
        matched = _match_columns(columns, kpi["keywords"])
        if not matched:
            continue
        col = matched[0]
        s = stats.get(col, {})
        kpi_results.append({
            "kpi": kpi["name"],
            "matched_column": col,
            "mean": s.get("mean"),
            "type": s.get("type", "numeric"),
            "top_value": s.get("top") if s.get("type") == "categorical" else None,
        })

    recommendations = []
    template = _RECOMMENDATION_TEMPLATES.get(industry, "")
    if kpi_results and template:
        top_kpi = kpi_results[0]
        col = top_kpi["matched_column"]
        value = top_kpi.get("mean")
        trend = (ml.get("future_prediction", {}) or {}).get("trend_direction", "stable")
        try:
            recommendations.append(template.format(col=col, value=round(value, 2) if value is not None else "the observed average", direction=trend))
        except Exception:
            pass

    best_target = (ana.get("ml_recommendation", {}) or {}).get("target_column", "")
    industry_label = "HR" if industry == "hr" else industry.replace("_", " ").title()
    if best_target and any(kw in best_target.lower() for kpi in _KPI_DEFINITIONS[industry] for kw in kpi["keywords"]):
        recommendations.append(f"The model's prediction target ('{best_target}') is itself a core {industry_label} KPI — operationalizing this model directly supports decision-making.")

    if not recommendations:
        recommendations.append(f"No {industry_label}-specific columns were confidently matched in this dataset — KPI mapping is approximate for generic datasets.")

    return {
        "available": True,
        "industry": industry,
        "industry_label": industry_label,
        "matched_kpis": kpi_results,
        "recommendations": recommendations[:4],
        "all_industries": INDUSTRIES,
    }
